.TH MONSHELL 1 monshell\-0.1
.SH NAME
monshell \- un minishell réalisé en C
.SH SYNOPSIS
.B minishell
.RB [\ monhelp
.IR help]
.RB [\ moncd
.IR moncd]
.RB [\ monsleep
.IR monsleep]
.RB [\ monexit
.IR monexit]
.SH DESCRIPTION
.B minishell
Notre minishell est un shell que nous avons développé en langage C dans le cadre du projet final du cours "Systèmes d'exploitation" de la seconde année de licence informatique à distance de l'Université Paris 8, sous la direction du professeur Philippe KISLIN.
.TP
.B \ monhelp
commande help de notre minishell:\br 
Tapez monhelp pour afficher et indications pour installer le manuel (Droits administrateurs nécessaires).
.TP
.B \ moncd
commande moncd de notre minishell:\br 
Tapez moncd <répertoire> ou moncd <..> ou moncd pour aller dans le HOME.
.TP
.B \ monsleep
commande monsleep de notre minishell:\br 
Tapez monsleep <args1><unité> ... <argsN><unité>
.TP
.B \ monexit
commande monexit de notre minishell:\br 
Tapez monexit dans le minishell sans argument.
.SH AUTEUR
.B Dominique ERIN at UnivP8
.SH DROITS
.B GNU minishell Tous droits réservés
